import { MetadataRoute } from "next";
import { siteConfig } from "@/lib/metadata";

/**
 * Generate robots.txt file
 * This is automatically generated by Next.js and served at /robots.txt
 */
export default function robots(): MetadataRoute.Robots {
  return {
    rules: {
      userAgent: "*",
      allow: "/",
      disallow: ["/api/", "/admin/"], // Disallow API routes and admin if they exist
    },
    sitemap: `${siteConfig.url}/sitemap.xml`,
  };
}

